.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH TRANSMAGEDDON 1 "October 14, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
transmageddon \-  multimedia transcoder for portable devices
.SH SYNOPSIS
.B transmageddon
.SH DESCRIPTION
This manual page documents briefly the
.B transmageddon
command.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBTransmageddon\fP is a video transcoder for the GNOME Desktop which allows
user to encode audio and video streams for a wide variety of portable devices.
.PP
It also supports almost any format as its input and can generate a very large
host of output files.
.PP
.B Transmageddon
has been written with Python and GTK+2, and after installing the application
you can run it from the
.B Applications
menu.
.SH AUTHOR
transmageddon was written by Christian Schaller <uraeus@gnome.org>.
.PP
This manual page was written by Alessio Treglia <quadrispro@ubuntu.com>.
